swagger: "2.0"
info:
  version: 1.0.0
  title: "trentose2jan12-dg"
  description: Semplice API per la gestione di un insieme di astronauti
  termsOfService: http://swagger.io/terms/
  contact:
    name: Daniele Giuliani
    email: daniele.giuliani@studenti.unitn.it
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: trentose2jan12-dg.herokuapp.com
basePath: /api/v1/
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /astronauts:
    get:
      description: |
        Ritorna la lista di tutti gli astronauti.
      parameters:
        - name: lastName
          in: query
          description: Filtro per cognome
          required: false
          type: string
        - name: id
          in: query
          description: Filtro per ID
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: Lista degli asronauti
          schema:
            type: array
            items:
              $ref: '#/definitions/astronauts'
    post:
      description: Inserisce la entry per un nuovo astronauta
      parameters:
        - name: astronaut
          in: body
          description: Astronauta da aggiungere
          required: true
          schema:
            $ref: '#/definitions/newAstronaut'
      responses:
        200:
          description: "Astronauta aggiunto con ID: 500"
    put:
      description: Modifica la entry di un terterminato astronauta
      parameters:
        - name: astronaut
          in: body
          description: Astronauta da modificare
          required: true
          schema:
            $ref: '#/definitions/editAstronaut'
      responses:
        200:
          description: "Astronauta modificato!"
        404:
          description: "Astronauta non trovato!"
definitions:
  astronauts:
    required:
      - id
      - firstName
      - lastName
      - isInSpace
    properties:
      id:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      isInSpace:
        type: boolean
  newAstronaut:
    required:
      - firstName
      - lastName
      - isInSpace
    properties:
      firstName:
        type: string
      lastName:
        type: string
      isInSpace:
        type: boolean
  editAstronaut:
    required:
      - id
    properties:
      id:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      isInSpace:
        type: boolean